# Language
language: node_js
node_js:
  - "node"


# Branches to build
branches:
  only:
    - master

# Build both library and samples
# We want any of these steps to fail the entire build
# We're also doing the install step here too, as we need
# the results of previous builds to install future builds
script:
  - ng new app 
    && npm install ngx-file-drop
    && ng build 
# Notifications
notifications:
  email:
    recipients:
      - georgi.peltekov@accedia.com
    on_success: change
    on_failure: change